version: '3.8'

services:
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8501:8501"
  #   depends_on:
  #     - backend
  #   env_file:
  #     - ./frontend/.env
  #   networks:
  #     - mary-network

  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   env_file:
  #     - ./backend/.env
  #   ports:
  #     - "8000:8000"
  #   networks:
  #     - mary-network
  
  chromadb:
    image: chromadb/chroma:latest
    volumes:
      - ./chromadb:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=${ANONYMIZED_TELEMETRY:-TRUE}
    ports:
      - 8000:8000
    networks:
      - cryptowatch-network

networks:
  cryptowatch-network:
    driver: bridge